In [17]:
text = """Under the hood, these functions simply create a pattern object for you and 
call the appropriate method on it. They also store the compiled object in a cache, so future calls using the same RE won’t need to parse the pattern again and again."""

# Count Lines

In [20]:
def countLines(text):
    n = text.split("\n")
    return len(n)

In [21]:
countLines(text)

2

# Count Sentense

In [ ]:
import re

In [22]:
def countSentense(text):
    l = re.compile("[.]\s[A-Z]").split(text)
    return len(l)   

In [23]:
countSentense(text)

2

# Count Words

In [32]:
def countWords(text):
    l = text.split(" ")
    s = set(l)
    return len(l),len(s)

In [34]:
countWords(text)

(44, 36)

# Frequncy of word The

In [53]:
def countGivenWord(text,word):
    #return text.lower().count(word.lower())
    c = list(1 for match in re.finditer(word.lower(),text.lower()))
    return len(c)

In [55]:
countGivenWord(text,"The")

7

# Scalar 

In [1]:
import numpy as np
import math
import sympy


In [39]:
w = np.array([2, 3, 4])
v1 = np.array([5, 6, 8])
v2 = np.array([3, 3, 4])

r = (np.column_stack((v1,v2,w)))


r[1] = np.divide(r[1],3)

r[2] = np.divide(r[2],3)

r[2] = np.subtract(r[1],r[2])

print(r)
l1 = [[*r[0,0:2]], [*r[1,0:2]]]
l2= [r[0,2],r[1,2]]
print("--------------")
print(l1)
print("--------------")
print(l2)
l2 = list(filter(lambda x:x != 0, l2))
ans = np.linalg.solve(l1,l2)
a = np.ceil(ans[0]) 
b=np.floor(ans[1])

print("Value of K1,K2 is {0} and {1}".format(a,b))

[[5 3 2]
 [2 1 1]
 [0 0 0]]
--------------
[[5, 3], [2, 1]]
--------------
[2, 1]
Value of K1,K2 is 1.0 and -1.0


In [ ]:
w = np.array([2, 3, 4])
v1 = np.array([5, 6, 8])
v2 = np.array([3, 3, 4])

a=np.column_stack([v1,v2])
b=np.linalg.lstsq(a,w)

c,d=b[0]
